on:
  push:
    branches:
    - main
    tags:
    - 'v*'

name: Release policy

jobs:

  test:
    name: run tests and linters
    uses: kubewarden/github-actions/.github/workflows/reusable-test-policy-rust.yml@v1

  release:
    needs: test
    permissions:
      # Required to push to GHCR
      contents: write
      packages: write
      # Required by cosign keyless signing
      id-token: write

    uses: kubewarden/github-actions/.github/workflows/reusable-release-policy-rust.yml@v1
    with:
      input-wasm: user_group_psp
      oci-target: ghcr.io/${{ github.repository_owner }}/policies/user-group-psp
    secrets:
      workflow-pat: ${{ secrets.WORKFLOW_PAT }}
